#ifndef AR3DVENGINE_OPENCV3_DEFINITION_H
#define AR3DVENGINE_OPENCV3_DEFINITION_H

#define OPENCV_VERSION_3

#ifdef OPENCV_VERSION_3
#define CV_CAP_PROP_FRAME_WIDTH cv::CAP_PROP_FRAME_WIDTH
#define CV_CAP_PROP_FRAME_HEIGHT cv::CAP_PROP_FRAME_HEIGHT
#define CV_THRESH_BINARY cv::THRESH_BINARY
#define CV_DIST_L2 cv::DIST_L2
#define CV_RETR_LIST cv::RETR_LIST
#define CV_RETR_EXTERNAL cv::RETR_EXTERNAL
#define CV_CHAIN_APPROX_NONE cv::CHAIN_APPROX_NONE
#define CV_BGR2GRAY cv::COLOR_BGR2GRAY
#define CV_RGB2GRAY cv::COLOR_RGB2GRAY
#define CV_SORT_EVERY_ROW cv::SORT_EVERY_ROW
#define CV_SORT_EVERY_COLUMN cv::SORT_EVERY_COLUMN
#define CV_SORT_ASCENDING cv::SORT_ASCENDING
#define CV_SORT_DESCENDING cv::SORT_DESCENDING
#endif

#endif //AR3DVENGINE_OPENCV3_DEFINITION_H
